[project]
name = "agentic-context-engineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.2.7",
    "langchain-ollama>=1.0.1",
    "pytest>=9.0.2",
]
