[project]
name = "corpus-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "TomsBicans", email = "tomsbicans@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
corpus-scraper = "corpus_scraper.main:main"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"
